#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# (wmake libso BCs && wmake && wmake rhoCentralDyMFoam)

cd src 

wmake all 2>&1 | tee log.wmake.all

wmake all applications 2>&1 | tee log.wmake.all.applications

# ----------------------------------------------------------------- end-of-file
